#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoFLF.Negocios
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CursoFLF")]
	public partial class DbClientesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertClientes(Clientes instance);
    partial void UpdateClientes(Clientes instance);
    partial void DeleteClientes(Clientes instance);
    #endregion
		
		public DbClientesDataContext() : 
				base(global::CursoFLF.Negocios.Properties.Settings.Default.CursoFLFConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbClientesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbClientesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbClientesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbClientesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Clientes> Clientes
		{
			get
			{
				return this.GetTable<Clientes>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_Clientes")]
	public partial class Clientes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cli_Id;
		
		private string _Cli_Nome;
		
		private string _Cli_Endereco;
		
		private string _Cli_Bairro;
		
		private string _Cli_Estado;
		
		private string _Cli_Telefone;
		
		private string _Cli_Celular;
		
		private string _Cli_Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCli_IdChanging(int value);
    partial void OnCli_IdChanged();
    partial void OnCli_NomeChanging(string value);
    partial void OnCli_NomeChanged();
    partial void OnCli_EnderecoChanging(string value);
    partial void OnCli_EnderecoChanged();
    partial void OnCli_BairroChanging(string value);
    partial void OnCli_BairroChanged();
    partial void OnCli_EstadoChanging(string value);
    partial void OnCli_EstadoChanged();
    partial void OnCli_TelefoneChanging(string value);
    partial void OnCli_TelefoneChanged();
    partial void OnCli_CelularChanging(string value);
    partial void OnCli_CelularChanged();
    partial void OnCli_EmailChanging(string value);
    partial void OnCli_EmailChanged();
    #endregion
		
		public Clientes()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cli_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Cli_Id
		{
			get
			{
				return this._Cli_Id;
			}
			set
			{
				if ((this._Cli_Id != value))
				{
					this.OnCli_IdChanging(value);
					this.SendPropertyChanging();
					this._Cli_Id = value;
					this.SendPropertyChanged("Cli_Id");
					this.OnCli_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cli_Nome", DbType="NVarChar(50)")]
		public string Cli_Nome
		{
			get
			{
				return this._Cli_Nome;
			}
			set
			{
				if ((this._Cli_Nome != value))
				{
					this.OnCli_NomeChanging(value);
					this.SendPropertyChanging();
					this._Cli_Nome = value;
					this.SendPropertyChanged("Cli_Nome");
					this.OnCli_NomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cli_Endereco", DbType="NVarChar(50)")]
		public string Cli_Endereco
		{
			get
			{
				return this._Cli_Endereco;
			}
			set
			{
				if ((this._Cli_Endereco != value))
				{
					this.OnCli_EnderecoChanging(value);
					this.SendPropertyChanging();
					this._Cli_Endereco = value;
					this.SendPropertyChanged("Cli_Endereco");
					this.OnCli_EnderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cli_Bairro", DbType="NVarChar(50)")]
		public string Cli_Bairro
		{
			get
			{
				return this._Cli_Bairro;
			}
			set
			{
				if ((this._Cli_Bairro != value))
				{
					this.OnCli_BairroChanging(value);
					this.SendPropertyChanging();
					this._Cli_Bairro = value;
					this.SendPropertyChanged("Cli_Bairro");
					this.OnCli_BairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cli_Estado", DbType="NVarChar(50)")]
		public string Cli_Estado
		{
			get
			{
				return this._Cli_Estado;
			}
			set
			{
				if ((this._Cli_Estado != value))
				{
					this.OnCli_EstadoChanging(value);
					this.SendPropertyChanging();
					this._Cli_Estado = value;
					this.SendPropertyChanged("Cli_Estado");
					this.OnCli_EstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cli_Telefone", DbType="NVarChar(50)")]
		public string Cli_Telefone
		{
			get
			{
				return this._Cli_Telefone;
			}
			set
			{
				if ((this._Cli_Telefone != value))
				{
					this.OnCli_TelefoneChanging(value);
					this.SendPropertyChanging();
					this._Cli_Telefone = value;
					this.SendPropertyChanged("Cli_Telefone");
					this.OnCli_TelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cli_Celular", DbType="NVarChar(50)")]
		public string Cli_Celular
		{
			get
			{
				return this._Cli_Celular;
			}
			set
			{
				if ((this._Cli_Celular != value))
				{
					this.OnCli_CelularChanging(value);
					this.SendPropertyChanging();
					this._Cli_Celular = value;
					this.SendPropertyChanged("Cli_Celular");
					this.OnCli_CelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cli_Email", DbType="NVarChar(50)")]
		public string Cli_Email
		{
			get
			{
				return this._Cli_Email;
			}
			set
			{
				if ((this._Cli_Email != value))
				{
					this.OnCli_EmailChanging(value);
					this.SendPropertyChanging();
					this._Cli_Email = value;
					this.SendPropertyChanged("Cli_Email");
					this.OnCli_EmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
